INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (1, 'Launch Website', 0, 'URL', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (2, 'Click', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (3, 'Wait', 0, 'Time', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (4, 'Enter Text', 1, 'Text', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (5, 'Enter Password', 1, 'Password', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (6, 'Maximize Browser', 0, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (7, 'Close Browser', 0, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (8, 'Wait Until Object Enabled', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (9, 'Wait Until Object Disabled', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (10, 'Wait Until Object Selected', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (11, 'Wait Until Object Not Selected', 1, 'Timout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (12, 'Wait Until Object Located', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (13, 'Wait Until Objects Located', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (14, 'Wait Until Object Visible', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (15, 'Wait Until Object Not Visible', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (16, 'Wait Until Object Text Contains', 1, 'Timeout', 'String', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (17, 'Wait Until Object Text Is', 1, 'Timeout', 'String', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (18, 'Wait Until Object Text Matches', 1, 'Timeout', 'RegEx', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (19, 'Wait Until Object Staleness Of', 1, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (20, 'Wait Until Title Contains', 1, 'Timeout', 'RegEx', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (21, 'Wait Until Title Is', 1, 'Timeout', 'String', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (22, 'Wait Until Title Matches', 1, 'Timeout', 'RegEx', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (23, 'Wait Until Url Contains', 1, 'Timeout', 'String', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (24, 'Wait Until Url Is', 1, 'Timeout', 'String', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (25, 'Wait Until Url Matches', 1, 'Timeout', 'RegEx', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (26, 'Wait Until Alert Present', 0, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (27, 'Wait Until Able To Switch Frame', 0, 'Timeout', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (28, 'Press Button', 1, 'Button', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (29, 'Double Click', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (30, 'Right Click', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (31, 'Refresh Page', 0, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (32, 'Generate Random Number', 0, 'Length', 'Output', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (33, 'Console Log', 0, 'Value', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (34, 'Get Page Title', 0, 'Output', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (36, 'Clear Input', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (37, 'Scroll To Object', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (38, 'Scroll To End', 0, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (39, 'Scroll To Top', 0, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (40, 'Click By Javascript', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (42, 'Click Link By Text', 0, 'Text', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (43, 'Click Link By Partial Text', 0, 'Text', NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (44, 'Hover Mouse', 1, NULL, NULL, NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (45, 'Copy Text', 0, 'Text', 'Output', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (46, 'Copy Password', 0, 'Password', 'Output', NULL);
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (47, 'Combine String', 0, 'Value1', 'Value2', 'Output');
INSERT INTO `actionevents` (`id`, `name`, `object`, `parameter1`, `parameter2`, `parameter3`) VALUES (48, 'Get Current Date Time', 0, 'Format', 'Output', NULL);
