export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const UPDATE_USER_DETAIL_REQUEST = "UPDATE_USER_DETAIL_REQUEST";
export const UPDATE_USER_DETAIL_SUCCESS = "UPDATE_USER_DETAIL_SUCCESS";
export const UPDATE_USER_DETAIL_FAILURE = "UPDATE_USER_DETAIL_FAILURE";

export const ROLE_REQUEST = "ROLE_REQUEST";
export const ROLE_SUCCESS = "ROLE_SUCCESS";
export const ROLE_FAILURE = "ROLE_FAILURE";

export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const ADD_PERMISSION_TO_ROLE_SUCCESS = "ADD_PERMISSION_TO_ROLE_SUCCESS";
export const REMOVE_PERMISSION_FROM_ROLE_SUCCESS =
  "REMOVE_PERMISSION_FROM_ROLE_SUCCESS";

export const TEAM_REQUEST = "TEAM_REQUEST";
export const TEAM_FAILURE = "TEAM_FAILURE";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const ADD_TEAM_MEMBER_SUCCESS = "ADD_TEAM_MEMBER_SUCCESS";
export const REMOVE_TEAM_MEMBER_SUCCESS = "REMOVE_TEAM_MEMBER_SUCCESS";

export const LOGOUT = "LOGOUT";
