export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL";
export const LOGOUT = "LOGOUT";
